# Generated by Django 3.2 on 2021-04-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no category', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(default='no category', max_length=255),
        ),
    ]
