# Generated by Django 3.2 on 2021-04-29 22:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20210429_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
