# Generated by Django 3.2 on 2021-04-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_alter_artwork_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='snippet',
            field=models.CharField(default='Snippet preview of the artwork description', max_length=255),
        ),
    ]
