# Generated by Django 3.2 on 2021-05-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20210501_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='artsite/images/default-profile.png', null=True, upload_to='images/profile/'),
        ),
    ]
